### ISSUE TITLE
[Feature] grafana dashboard should work out of the box

### ISSUE THREAD

**Issue by ziliangpeng** [sgl-project/sglang#3328]
### Checklist

- [x] 1. If the issue you raised is not a feature but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [x] 2. Please use English, otherwise it will be closed.

### Motivation

we should make prometheus metrics and grafana dashboard ready to use out of the box to avoid requiring any user manual set up. this will streamline the accessibility of observability and reduce efforts required to support users.

### task check list

- [ ] in the metrics doc, remind user to run sglang server with `--enable-metrics`

_No response_

**Comment by PopSoda2002** [comment]
I will take that together!

**Comment by blacker521** [comment]
I will take that together

**Comment by ziliangpeng** [comment]
# What

From the [example](https://github.com/sgl-project/sglang/tree/main/examples/monitoring) provided to display [production metrics](https://github.com/sgl-project/sglang/blob/main/docs/references/production_metrics.md), a few things are missing on the grafana UI that require manual steps:
- missing data source to connect to the prometheus instance
- missing dashboards that requires manual importing

There might be more missing pieces (as we work along this issue) to have a completely manual-free grafana example.
The acceptance of this issue is to run `docker compose -f compose.yaml -p monitoring up` and production metrics is viewable on `localhost:3000/{path to dashboard}` showing sglang metrics.


# How

We most likely need to create our own Dockerfil based off of the grafana base image, and manipulate the configuration in grafana image to the right state.

### automating data source
this may be achieved by just putting a file in `/etc/grafana/provisioning/datasources/`.
an example (only example) of the config file would be something like 
```
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://localhost:9090
    jsonData:
      httpMethod: POST
      prometheusType: Prometheus
      prometheusVersion: 2.44.0
      exemplarTraceIdDestinations:
        - name: traceID
          datasourceUid: my_jaeger_uid
    version: 1
    editable: false

```
the exactly location and format of the file can be explored from official documents, or just find it in the container after manually creating a data source.

### automating dashboard
similarly we can create dashboard by putting the right file in the right place. 
TODO: will add more details when we're at this step.

**Comment by blacker521** [comment]
just like this one?
https://github.com/sgl-project/sglang/blob/main/docs/references/production_metrics.md

**Comment by zhaochenyang20** [comment]
@blacker521 will make it easier

**Comment by blacker521** [comment]
@zhaochenyang20 return this information in JSON? how can I contribute it?

**Comment by blacker521** [comment]
Is this feature going anywhere? Can I be a part of it?

**Comment by zhaochenyang20** [comment]
@blacker521 @PopSoda2002 and @ziliangpeng is on this part. We do not need more people right now. Thanks!

**Comment by PopSoda2002** [comment]
Fixed by PR: https://github.com/sgl-project/sglang/pull/4718

**Comment by arcsun** [comment]
But it's still not out-of-the-box in 2026, unlike vLLM and any other tools?
 In Grafana, it should just be importing JSON, choosing a datasource, and all done, without involving any server operations.
