### ISSUE TITLE
[Bug] --enable-metrics raise Error

### ISSUE THREAD

**Issue by xihuai18** [sgl-project/sglang#4157]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The bug has not been fixed in the latest version.
- [x] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [ ] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [ ] 5. Please use English, otherwise it will be closed.

### Describe the bug

Run any model with `--enable-metrics` for hours, then raise

```
[2025-03-07 02:34:00] TokenizerManager hit an exception: Traceback (most recent call last):
  File "/path/to/sglang/python/sglang/srt/managers/tokenizer_manager.py", line 1119, in print_exception_wrapper
    await func()
  File "/path/to/sglang/python/sglang/srt/managers/tokenizer_manager.py", line 875, in handle_loop
    self._result_dispatcher(recv_obj)
  File "/path/to/sglang/python/sglang/utils.py", line 444, in __call__
    return fn(obj)
  File "/path/to/sglang/python/sglang/srt/managers/tokenizer_manager.py", line 956, in _handle_batch_output
    self.collect_metrics(state, recv_obj, i)
  File "/path/to/sglang/python/sglang/srt/managers/tokenizer_manager.py", line 1068, in collect_metrics
    self.metrics_collector.observe_one_finished_request(
  File "/path/to/sglang/python/sglang/srt/metrics/collector.py", line 259, in observe_one_finished_request
    self.cached_tokens_total.labels(**self.labels).inc(cached_tokens)
  File "/usr/local/conda/lib/python3.9/site-packages/prometheus_client/metrics.py", line 313, in inc
    raise ValueError('Counters can only be incremented by non-negative amounts.')
ValueError: Counters can only be incremented by non-negative amounts.
```

### Reproduction

Run any model with `--enable-metrics` for hours

### Environment

A100

**Comment by xihuai18** [comment]
@xiezhq-hermann @Edenzzzz I think it results from the refactor in mem_pool

**Comment by xiezhq-hermann** [comment]
@Ying1123 @merrymercy do you have any idea about the bug regarding to `--enable-metrics`?

**Comment by Tmn07** [comment]
I also encountered the same issue.
at sglang0.4.3.post4 A800

**Comment by yangrong688** [comment]
also encountered the same issue:

[2025-03-16 20:53:50] TokenizerManager hit an exception: Traceback (most recent call last):
  File "/root/miniconda3/envs/sglang/lib/python3.12/site-packages/sglang/srt/managers/tokenizer_manager.py", line 1119, in print_exception_wrapper
    await func()
  File "/root/miniconda3/envs/sglang/lib/python3.12/site-packages/sglang/srt/managers/tokenizer_manager.py", line 875, in handle_loop
    self._result_dispatcher(recv_obj)
  File "/root/miniconda3/envs/sglang/lib/python3.12/site-packages/sglang/utils.py", line 444, in __call__
    return fn(obj)
           ^^^^^^^
  File "/root/miniconda3/envs/sglang/lib/python3.12/site-packages/sglang/srt/managers/tokenizer_manager.py", line 956, in _handle_batch_output
    self.collect_metrics(state, recv_obj, i)
  File "/root/miniconda3/envs/sglang/lib/python3.12/site-packages/sglang/srt/managers/tokenizer_manager.py", line 1068, in collect_metrics
    self.metrics_collector.observe_one_finished_request(
  File "/root/miniconda3/envs/sglang/lib/python3.12/site-packages/sglang/srt/metrics/collector.py", line 259, in observe_one_finished_request
    self.cached_tokens_total.labels(**self.labels).inc(cached_tokens)
  File "/root/miniconda3/envs/sglang/lib/python3.12/site-packages/prometheus_client/metrics.py", line 313, in inc
    raise ValueError('Counters can only be incremented by non-negative amounts.')
ValueError: Counters can only be incremented by non-negative amounts.

and find same issue in vllm project
https://github.com/vllm-project/vllm/issues/6642

**Comment by dblate** [comment]
+1

**Comment by MayDomine** [comment]
@zhaochenyang20 CC

**Comment by zhaochenyang20** [comment]
@xihuai18 hey, xihuai. I think this has been solved? what's the process?

**Comment by xihuai18** [comment]
> also encountered the same issue:
> 
> [2025-03-16 20:53:50] TokenizerManager hit an exception: Traceback (most recent call last): File "/root/miniconda3/envs/sglang/lib/python3.12/site-packages/sglang/srt/managers/tokenizer_manager.py", line 1119, in print_exception_wrapper await func() File "/root/miniconda3/envs/sglang/lib/python3.12/site-packages/sglang/srt/managers/tokenizer_manager.py", line 875, in handle_loop self._result_dispatcher(recv_obj) File "/root/miniconda3/envs/sglang/lib/python3.12/site-packages/sglang/utils.py", line 444, in **call** return fn(obj) ^^^^^^^ File "/root/miniconda3/envs/sglang/lib/python3.12/site-packages/sglang/srt/managers/tokenizer_manager.py", line 956, in _handle_batch_output self.collect_metrics(state, recv_obj, i) File "/root/miniconda3/envs/sglang/lib/python3.12/site-packages/sglang/srt/managers/tokenizer_manager.py", line 1068, in collect_metrics self.metrics_collector.observe_one_finished_request( File "/root/miniconda3/envs/sglang/lib/python3.12/site-packages/sglang/srt/metrics/collector.py", line 259, in observe_one_finished_request self.cached_tokens_total.labels(**self.labels).inc(cached_tokens) File "/root/miniconda3/envs/sglang/lib/python3.12/site-packages/prometheus_client/metrics.py", line 313, in inc raise ValueError('Counters can only be incremented by non-negative amounts.') ValueError: Counters can only be incremented by non-negative amounts.
> 
> and find same issue in vllm project [vllm-project/vllm#6642](https://github.com/vllm-project/vllm/issues/6642)

This bug is not fixed but just ignored in vllm, ref: https://github.com/vllm-project/vllm/pull/10430

**Comment by xihuai18** [comment]
https://github.com/vllm-project/vllm/issues/10583 

Under my test, this bug is also not caused by querying with same request id.

**Comment by xihuai18** [comment]
Related PR that may caused this problem: 
1. https://github.com/sgl-project/sglang/pull/1853
2. https://github.com/sgl-project/sglang/pull/119

**Comment by xiezhq-hermann** [comment]
I identified and fixed this problem in this PR: https://github.com/sgl-project/sglang/pull/4660. Let me know if this problem persists on your case.
